- name: Install Prometheus
 hosts: prometheus
 tasks:
 - name: Install required packages
   apt:
     name: "{{ item }}"
     state: present
   with_items:
     - prometheus
     - prometheus-node-exporter
     - prometheus-alertmanager

 - name: Copy Prometheus configuration file
   copy:
     src: prometheus.yml
     dest: /etc/prometheus/prometheus.yml
   notify:
     - restart prometheus

  - name: Restart Prometheus
    hosts: prometheus
    tasks:
  - name: Restart Prometheus service
    service:
     name: prometheus
     state: restarted