apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewfilmes
spec:
  replicas: 10
  selector:
    matchLabels:
      app: reviewfilmes
  template:
    metadata:
      labels:
        app: reviewfilmes
    spec:
      containers:
        - name: review-filmes
          image: rfahham/review-filmes:v1
          env:
          - name: ASPNETCORE_HTTP_PORTS
            value: "8080"
          - name: ConnectionStrings__DefaultConnection
            value: "Host=postgre;Database=reviewfilmes;Username=reviewfilmes;Password=Passw0rd20244!"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reviewfilmes
spec:
  selector:
    app: reviewfilmes
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
    