name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs: 
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Exemplo
        run: echo "CI"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Exemplo
        run: echo "CD"
  